<?php require './laycut/header.php';?>

<section id="gallery">
        <h2>Galería de Fotos para Grados</h2>
        <div class="gallery">
            <img src="./img/grado 1.jpg" alt="Foto 1">
            <img src="./img/grado 2.jpg" alt="Foto 2">
            <img src="./img/grado 3.jpg" alt="Foto 3">
            <img src="./img/grado 4.jpg" alt="Foto 4">
            <img src="./img/grado 5.jpg" alt="Foto 5">
            <img src="./img/grado 6.jpg" alt="Foto 6">
            <img src="./img/grado 7.jpg" alt="Foto 7">
            <img src="./img/grado 8.jpg" alt="Foto 8">
        </div>
    </section>

    <?php require './laycut/footer.php';?>